import { appendFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { currentTrace } from './events.js';
import { STATE_DIR } from '../config.js';
const DIR = `${STATE_DIR}/logs`, MAX_AGE_DAYS = 14, ready = mkdir(DIR, { recursive: true }).catch(() => {});
function write(name: string, data: Record<string, unknown>) { const trace = currentTrace(); ready.then(() => appendFile(`${DIR}/${name}-${new Date().toISOString().slice(0, 10)}.jsonl`, JSON.stringify({ t: new Date().toISOString(), traceId: trace?.traceId || null, ...data }) + '\n')).catch(() => {}); }
function count(r: any): number | null { return Array.isArray(r) ? r.length : Array.isArray(r?.tracks) ? r.tracks.length : null; }
function shortlist(p: unknown) { const t=String(p||''), m='Grounded candidates discovered for this pick:\n', i=t.indexOf(m); if(i<0)return {count:null,uniqueArtists:null}; try { const a=JSON.parse(t.slice(i+m.length)); return Array.isArray(a)?{count:a.length,uniqueArtists:new Set(a.map((x:any)=>String(x?.artist||'').trim()).filter(Boolean)).size}:{count:null,uniqueArtists:null}; } catch { return {count:null,uniqueArtists:null}; } }
export function logInferencePerformance(c: any) { write('inference-performance',{kind:c.kind,ok:!!c.ok,ms:c.ms??null,model:c.model??null,via:c.via??null,inputTokens:c.usage?.input??null,outputTokens:c.usage?.output??null,totalTokens:c.usage?.total??null,modelMs:c.perf?.modelMs??null,tokensPerSec:c.perf?.tokensPerSec??null,error:c.error??null}); }
export function logDiscoveryRoute(c: any) { if(c.kind!=='djProducerRoute')return; const tools=(c.toolCalls||[]).filter((x:any)=>x?.name!=='done').map((x:any)=>({name:x.name,resultCount:count(x.result),error:x.result?.error||null})); write('discovery-routes',{ok:!!c.ok,ms:c.ms??null,steps:c.steps??tools.length,candidates:tools.reduce((n:number,x:any)=>n+Math.max(0,x.resultCount||0),0),tools,error:c.error??null}); }
export function logShortlistPick(c: any) { if(c.kind!=='djProducerSelect')return; const s=shortlist(c.user), x=(c.toolCalls||[]).find((x:any)=>x?.args?.id||x?.result?.id); let selectedId=x?.args?.id||x?.result?.id||null; if(!selectedId){try{selectedId=JSON.parse(String(c.response||'{}')).id||null}catch{}} write('shortlist-picks',{ok:!!c.ok,ms:c.ms??null,candidates:s.count,uniqueArtists:s.uniqueArtists,selectedId,inputTokens:c.usage?.input??null,outputTokens:c.usage?.output??null,error:c.error??null}); }
export async function pruneOldAnalysisLogs(days=MAX_AGE_DAYS) { const cutoff=new Date(Date.now()-days*86400000).toISOString().slice(0,10); let names:string[];try{names=await readdir(DIR)}catch{return 0}let removed=0;for(const name of names){const m=name.match(/^(discovery-routes|shortlist-picks|inference-performance)-(\d{4}-\d{2}-\d{2})\.jsonl$/);if(!m||m[2]>=cutoff)continue;try{await unlink(DIR+'/'+name);removed++}catch{}}return removed; }
